apiVersion: v1
kind: Service
metadata:
  name: {{ include "order-service.fullname" . }}
spec:
  selector:
    app: order-service
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
